#!/bin/bash

# Step 1: Created Directory
mkdir Testdirectory

# Step 2: Navigating into Testdirectory
cd Testdirectory

# Step 3: Create a file in Testdirectory
touch testfile.txt

# Step 4: writing a text in a file 
echo "This is my bash learning journey testfile.txt." > myfile.txt

# Step 5: Display the contents of the file
cat testfile.txt

